photoalbum/photoalbum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photoalbum_site.urls')),
    path('ckeditor/', include ('ckeditor_uploader.urls')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

photoalbum/photoalbum_site/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('post/<slug:slug>', views.post, name='post'),
    path('posts/', views.posts, name='posts'),
    path('profile/', views.profile, name='profile'),

    # crud

    path('create_post/', views.createPost, name='create_post'),
    path('update_post/<slug:slug>/', views.updatePost, name='update_post'),
    path('delete_post/<slug:slug>/', views.deletePost, name='delete_post'),

    path('send_email/', views.sendEmail, name='send_email'),

]

photoalbum/photoalbum_site/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

class Tag (models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post (models.Model):
    headline = models.CharField(max_length=100)
    subheadline = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(null=True, blank=True, upload_to="images", default="/images/placeholder.png")
    body = RichTextUploadingField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(null=True)
    tags = models.ManyToManyField(Tag, null=True)
    slug = models.SlugField(null=True, blank=True)


    def __str__(self):
        return self.headline

    def save(self, *args, **kwargs):

        if self.slug == None:
            slug = slugify(self.headline)

            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = slugify(self.headline) + '-' + str(count)
                has_slug = Post.objects.filter(slug=slug).exists()
            self.slug = slug
        super().save(*args, **kwargs)


class PostImage(models.Model):
    post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE)
    images = models.ImageField(upload_to="images")

    def __str__(self):
        return self.post.headline

photoalbum/photoalbum_site/forms.py
from django import forms
from django.forms import ModelForm

from .models import Post, PostImage

class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = '__all__'

        widgets = {
            'tags': forms.CheckboxSelectMultiple,
            'featured': forms.CheckboxInput,
        }

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)  # Call to ModelForm constructor
        self.fields['tags'].widget.attrs['height'] = 100
        #self.fields['long_desc'].widget.attrs['rows'] = 20


"""class PostImageForm(ModelForm):
    class Meta:
        model = PostImage
        extra = 1
        max_num = 10
        fields = ('images',)
        #exclude = ('post',)"""

photoalbum/photoalbum_site/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Post, PostImage
from .forms import PostForm
from .filters import PostFilter

from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string

def post (request,slug):
    post = Post.objects.get(slug=slug)
    photos = PostImage.objects.filter(post=post)
    context = {'post': post, 'photos':photos}
    return render(request, 'photoalbum_site/post.html', context)

def posts(request):
    posts = Post.objects.filter(active=True)
    myFilter = PostFilter(request.GET, queryset=posts)
    posts = myFilter.qs

    page = request.GET.get('page')
    paginator = Paginator(posts, 3)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts':posts, 'myFilter':myFilter}
    return render(request, 'photoalbum_site/posts.html', context)

def home(request):
    posts = Post.objects.filter(active=True, featured=True)[0:3]
    context = {'posts':posts}
    return render(request, 'photoalbum_site/index.html', context)

def profile (request):
    return render(request, 'photoalbum_site/profile.html')

# crud

@login_required(login_url='home')
def createPost(request):
    form = PostForm()

    if request.method=='POST':
        form=PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('posts')

    context={'form':form}
    return render (request, 'photoalbum_site/post_form.html',context)

@login_required(login_url='home')
def updatePost(request, slug):
    post = Post.objects.get(slug=slug)
    form = PostForm(instance=post)

    if request.method=='POST':
        form=PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        return redirect('posts')

    context={'form':form}
    return render (request, 'photoalbum_site/post_form.html',context)

@login_required(login_url='home')
def deletePost(request, slug):
    post = Post.objects.get(slug=slug)
    if request.method=='POST':
        post.delete()
        return redirect('posts')
    context = {'item':post}
    return render(request, 'photoalbum_site/delete.html', context)

def sendEmail(request):

	if request.method == 'POST':

		template = render_to_string('photoalbum_site/email_template.html',
                                    {'name':request.POST['name'],
                                     'email':request.POST['email'],
                                     'message':request.POST['message'],
                                     })

		email = EmailMessage(
			request.POST['subject'],
			template,
			settings.EMAIL_HOST_USER,
			['sonitkach@gmail.com']
			)

		email.fail_silently=False
		email.send()
	return render(request, 'photoalbum_site/email_sent.html')

photoalbum/photoalbum_site/templates/photoalbum_site/delete.html
{% extends 'photoalbum_site/main.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
<div class="main-container">
	<form method="POST" action="">
		{% csrf_token %}
		<p>Are you sure you want to delete {{item}}?</p>
		<input class="btn btn-danger" type="submit" value="Confirm">
        <a class="btn btn-primary" href="{% url 'posts' %}">&laquo Back To Posts</a>
	</form>
</div>

{% endblock content %}

photoalbum/photoalbum_site/templates/photoalbum_site/email_sent.html
{% extends 'photoalbum_site/main.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


<style type="text/css">
	html, body{
		height: 100%;
	}

	#page-wrapper{
		height: 100%;
		display: flex;
		justify-content: center;
		align-items: center;
		text-align: center;
		background-color: #eaeaea;
	}

	#success-box{
		max-width: 800px;
		height: auto;
		background-color: #fff;
		border:1px solid #888;
		border-radius: 5px;
		padding: 15px;
	}

	#success-box p{
		font-size: 18px;
	}

</style>

<div id="page-wrapper">
	<div id="success-box" class="content-block">
		<h2>Thanks for reaching out!</h2>
		<p>Your message was successfully sent. I will do my best to get back to you in a timely manner :)</p>
		<a id="back-btn" class="btn btn-dark" href="{% url 'home' %}">BACK TO HOME PAGE</a>
	</div>
</div>

{% endblock content %}

photoalbum/photoalbum_site/templates/photoalbum_site/email_template.html
{{message}}

{{name}}

{{email}}

photoalbum/photoalbum_site/templates/photoalbum_site/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
</head>
<body>
<h1> home </h1>
</body>
</html>

photoalbum/photoalbum_site/templates/photoalbum_site/index.html
{% extends 'photoalbum_site/main.html' %}
{% load static %}
{% block content %}
<html>
<head>
	<title>Photoalbum</title>


	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>

<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
<link id="theme-style" rel="stylesheet" type="text/css" href="">


	<section class="s1">
		<div class="main-container">
			<div class="greeting-wrapper">
				<h1>Hi, I'm Lorem Ipsum </h1>
			</div>


			<div class="intro-wrapper">
				{% include 'photoalbum_site/navbar.html' %}

				<div class="left-column">
					<img id="profile_pic" src="{% static 'images/me.png' %}">
					<h5 style="text-align: center;line-height: 0;">Personalize Theme</h5>

					<div id="theme-options-wrapper">
						<div data-mode="light" id="light-mode" class="theme-dot"></div>
						<div data-mode="blue" id="blue-mode" class="theme-dot"></div>

					</div>

					<p id="settings-note">*Theme settings will be saved for<br>your next vist</p>
				</div>

				<div class="right-column">

					<div id="preview-shadow">
						<div id="preview">
							<div id="corner-tl" class="corner"></div>
							<div id="corner-tr" class="corner"></div>
							<h3>What I Do</h3>
							<p> I'm a photographer. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
							<div id="corner-br" class="corner"></div>
							<div id="corner-bl" class="corner"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">

			<div class="about-wrapper">
				<div class="about-me">
					<h4>More about me</h4>

					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque dapibus sapien fermentum sem facilisis facilisis.</p>


					<hr>

					<h4>My skills</h4>

					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <a target="_blank" href="{% static 'resume.pdf' %}">Download Resume</a></p>

					<div id="skills">
						<ul>
							<li>Skill 1</li>
							<li>Skill 2</li>
							<li>Skill 3</li>
							<li>Skill 4</li>
							<li>Skill 5</li>
						</ul>

						<ul>
							<li>Lorem ipsum 1</li>
							<li>Lorem ipsum 2</li>
							<li>Lorem ipsum 3</li>
							<li>Lorem ipsum 4</li>
							<li>Lorem ipsum 5</li>
						</ul>

					</div>

				</div>


				<div class="social-links">
					<img id="social_img" src=" {% static 'images/placeholder.png' %}">
					<h3>Find me on Pinterest & Instagram </h3>
					<a href="https://www.instagram.com/" class="fa fa-instagram"></a>
					<a href="https://www.pinterest.com/" class="fa fa-pinterest"></a>


				</div>
			</div>

		</div>
	</section>

	<section class="s1">
		<div class="main-container">
			<h3 style="text-align: center;">Some of my past projects</h3>

			<div class="post-wrapper">
				{% for post in posts %}
				<div>
					<div class="post">
						<img class="thumbnail" src="{{post.thumbnail.url}}">
						<div class="post-preview">
							<h6 class="post-title">{{post.headline}}</h6>
							<p class="post-intro">{{post.subheadline}}</p>
							<a href="{%  url 'post' post.slug %}">Read More</a>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>

			<p align="center">
				<a href="{% url 'posts' %}">View More</a>
			</p>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">
			<a href=""></a>
			<h3 style="text-align: center;">Get In Touch</h3>

			<form id="contact-form" method="POST" action="{% url 'send_email' %}">
				{% csrf_token %}
				<a name="contact"></a>

				<label>Name</label>
				<input class="input-field" type="text" name="name">

				<label>Subject</label>
				<input class="input-field" type="text" name="subject">

				<label>Email</label>
				<input class="input-field" type="text" name="email">

				<label>Message</label>
				<textarea class="input-field" name="message"></textarea>

				<input id="submit-btn" type="submit" value="Send">
			</form>
		</div>
	</section>

	<script type="text/javascript">
		let static = "static/css"
	</script>

	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>

{% endblock content %}
</body>
</html>

photoalbum/photoalbum_site/templates/photoalbum_site/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> photoalbum </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">
</head>
<body>

{% include 'photoalbum_site/navbar.html'%}

{% block content %}

{% endblock content %}
</body>
</html>

photoalbum/photoalbum_site/templates/photoalbum_site/navbar.html
<div class="nav-wrapper">

					<!-- Link around dots-wrapper added after tutorial video -->
    <a href="{% url 'home' %}">
        <div class="dots-wrapper">
            <div id="dot-1" class="browser-dot"></div>
            <div id="dot-2" class="browser-dot"></div>
            <div id="dot-3" class="browser-dot"></div>
        </div>
    </a>


    <ul id="navigation">
        <li><a href="{% url 'home' %}#contact">Contact</a></li>

        {% if request.user.is_authenticated %}
            <li><a href="{% url 'create_post' %}#">Create Post</a></li>
        {% endif %}

    </ul>
</div>

photoalbum/photoalbum_site/templates/photoalbum_site/post.html
{% extends 'photoalbum_site/main.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


<style type="text/css">
    img {
<!--        max-width: 100%;-->
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 100%;
        border: 2px solid #ddd;
        border-radius: 4px;
        padding: 5px;
        position: relative;
        overflow: hidden;
        object-fit: cover;
    }
</style>

<div class="main-container">
<!--    <img class="featured_image" src="{{post.thumbnail.url}}">-->
    <h1>{{post.headline}}</h1>
    <h4> {{post.subheadline}}</h4>

    <p>
        {{post.body | safe }}
    </p>

    <div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">
    <!--Indicators-->
    <ol class="carousel-indicators">
    {% for p in photos %}
      <li data-target="#carousel-example-1z" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.counter0 == 0 %} active {% endif %}"></li>
    {% endfor %}
    </ol>
    <!--/.Indicators-->
    <!--Slides-->
    <div class="carousel-inner" role="listbox">
      {% for p in photos %}
      <div class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}">
        <img class="d-block w-100" src="{{p.images.url}}" alt="">
      </div>
      {% endfor %}
      <!--/First slide-->
    <!--/.Slides-->
    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->
  </div>
</div>
    <br>
    <br>

{% endblock content %}

photoalbum/photoalbum_site/templates/photoalbum_site/post_form.html
{% extends 'photoalbum_site/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">

<style type="text/css">
    #div_id_tags > div{
        max-height: 100px;
        overflow-y: scroll;
        border: 1px solid #888;
        padding: 5px;
        border-radius: 5px;
    }
</style>

<div class="main-container">
    <h3>Post form </h3>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
<!--        {{ image_form }}-->
<!--        {{ image_form | crispy }}-->
        <br>
        <input class="btn btn-primary" type="submit" value="Submit Post">
    </form>
</div>


{% endblock content %}

photoalbum/photoalbum_site/templates/photoalbum_site/posts.html
{% extends 'photoalbum_site/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">

<style type="text/css">
	#id_tags {
		max-height: 100px;
        overflow-y: scroll;
        border: 1px solid #888;
        padding: 5px;
        border-radius: 5px;
	}
</style>

<div class="main-container">
    <h1> Posts </h1>

	<form id="searchForm" method="GET">
		{{myFilter.form|crispy }}
		<input class="btn btn-dark" type="submit" value="search">
	</form>

    <div class="post-wrapper">
		{% for post in posts %}
				<div>
					<div class="post">
						<img class="thumbnail" src="{{post.thumbnail.url}}">
						<div class="post-preview">
							<h6 class="post-title">{{post.headline}}</h6>
							<p class="post-intro">{{post.subheadline}}</p>
							<a href="{% url 'post' post.slug %}">Read More</a>

							{% if request.user.is_authenticated %}
								| <a href="{% url 'update_post' post.slug %}">Edit</a>
								| <a href="{% url 'delete_post' post.slug %}">Delete</a>
							{% endif %}
							<hr>
							{% for tag in post.tags.all %}
								<span class="tag">{{tag}} </span>
							{% endfor %}
							<hr>
						</div>
					</div>
				</div>
		{% empty%}
			<h3> No posts found :( </h3>
		{% endfor %}
	</div>

	<div class="row">

		{% if posts.has_other_pages %}

			<ul class="pagination">

				{% if posts.has_previous %}
					<li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}" class="page-link">&laquo</a></li>

					<li class="page-item"><a data-page="1" href="?page=1" class="page-link">First</a></li>
				{% endif %}


				{% for i in posts.paginator.page_range %}
					{% if posts.number == i %}
						<li class="page-item"><a class="active page-link">{{i}}</a></li>
					{% else %}
						<li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a></li>
					{% endif %}

				{% endfor %}


				{% if posts.has_next %}
					<li class="page-item"><a data-page="{{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}" class="page-link">Last</a></li>

					<li class="page-item"><a data-page="{{posts.next_page_number}}" href="?page={{posts.next_page_number}}" class="page-link">&raquo</a></li>
				{% endif %}
			</ul>

		{% endif %}
	</div>

</div>

<script type="text/javascript">
	let searchForm = document.getElementById('searchForm')
	let pageLinks = document.getElementsByClassName('page-link')

	for(var i=0; pageLinks.length > i; i++){

		pageLinks[i].addEventListener('click', function(e){
			e.preventDefault()
			let page = this.dataset.page
			console.log('Page:', page)
			searchForm.innerHTML += `<input value="${page}" name="page" hidden >`
			searchForm.submit()
		})

	}
</script>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


{% endblock content %}

photoalbum/photoalbum_site/templates/photoalbum_site/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
</head>
<body>
{% extends 'photoalbum_site/main.html' %}
{% block content %}
<h1> profile </h1>
{% endblock content %}
</body>
</html>